---
os: linux
serrvices: docker
language: minimal

addons:
  apt:
    packages:
      - pass

install: skip

env:
  - BUILD_TAG=centos7
  - BUILD_TAG=debian_stretch
  - BUILD_TAG=debian_buster
  - BUILD_TAG=ubuntu_16.04
  - BUILD_TAG=ubuntu_18.04

script: |
  docker build -f Dockerfile-${BUILD_TAG} -t thoteam/molecule_apache_openjdk8:${BUILD_TAG} . \
  && echo ${GITHUB_PASSWORD} | docker login -u ${GITHUB_USER} --password-stdin \
  && docker push thoteam/molecule_apache_openjdk8:${BUILD_TAG}
