---
os: linux
serrvices: docker
language: minimal
install: skip
addons:
  apt:
    packages:
      - pass

env:
  - BUILD_TAG=centos7
  - BUILD_TAG=debian_stretch
  - BUILD_TAG=debian_buster
  - BUILD_TAG=ubuntu_16.04
  - BUILD_TAG=ubuntu_18.04

script: |
  curl -fsSL "https://github.com/docker/docker-credential-helpers/releases/download/v0.6.3/docker-credential-pass-v0.6.3-amd64.tar.gz" | tar xv
  chmod + $(pwd)/docker-credential-pass

  gpg --batch --gen-key <<-EOF ; pass init $(gpg --no-auto-check-trustdb --list-secret-keys | grep ^sec | cut -d/ -f2 | cut -d" " -f1)
  %echo Generating a standard key
  Key-Type: DSA
  Key-Length: 1024
  Subkey-Type: ELG-E
  Subkey-Length: 1024
  Name-Real: Docker Thoteam
  Name-Email: ThoTeam@spamstinks.com
  Expire-Date: 0
  # Do a commit here, so that we can later print "done" :-)
  %commit
  %echo done
  EOF

  echo ${GITHUB_PASSWORD} | docker login -u ${GITHUB_USER} --password-stdin
  docker build -f Dockerfile-${BUILD_TAG} -t thoteam/molecule_apache_openjdk8:${BUILD_TAG} .
  docker push thoteam/molecule_apache_openjdk8:${BUILD_TAG}
