FROM centos:8

ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]

RUN dnf makecache && \
    dnf update -y && \
    dnf install -y \
        java-1.8.0-openjdk-headless \
        httpd \
        mod_ssl \
        python36 \
        sudo \
        bash \
        crontabs \
        rsync \
        policycoreutils \
        which && \
    sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && \
    dnf clean all;

CMD ["/usr/sbin/init"]
