FROM debian:bullseye

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y curl && \
    curl -o /usr/share/keyrings/adoptopenjdk.asc https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public && \
    echo 'deb [signed-by=/usr/share/keyrings/adoptopenjdk.asc] https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bullseye main' > /etc/apt/sources.list.d/adoptopenjdk.list && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    	sudo \
        adoptopenjdk-8-hotspot \
        systemd \
        apache2 \
        python3-apt \
        cron \
        rsync \
        curl \
        apt-transport-https && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    a2enmod ssl rewrite proxy proxy_http headers

CMD ["/lib/systemd/systemd"]
