FROM debian:bookworm

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    apt-get update && \
    apt-get install -y apt-utils wget gnupg software-properties-common sudo && \
    wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public > /etc/apt/keyrings/adoptium.asc && \
    echo 'deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb bookworm main' > /etc/apt/sources.list.d/adoptium.list && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        temurin-8-jdk \
        systemd \
        apache2 \
        python3 \
        python3-apt \
        cron \
        rsync \
        curl \
        apt-transport-https && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    a2enmod ssl rewrite proxy proxy_http headers

CMD ["/lib/systemd/systemd"]
