FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        systemd \
        apache2 \
        openjdk-8-jre-headless \
        python3-apt \
        sudo \
        ca-certificates \
        cron \
        rsync \
        curl \
        apt-transport-https && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    a2enmod ssl rewrite proxy proxy_http headers

CMD ["/lib/systemd/systemd"]
